### ISSUE TITLE
Video indexed as a different team's

### ISSUE THREAD

**Issue by ayoubkachkach** [meneses-pt/videogoals#2]
Moving this issue from the r/soccer post.

#### The problem:
Matches that have an affiliate of a team (e.g. Inter U19, Fiorentina W ...) are matched to matches of the original team (e.g. Inter, Fiorentina ...) if a game is played at a 2 day-interval.

#### Example:
[Fiorentina W - Inter W](https://videogoals.meneses.pt/fiorentina-w-inter-milano-w-20191215) picking up on Fiorentina - Inter games.

#### Potential cause of the problem:
Trigram search to fetch teams in [goals_populator.py](https://github.com/meneses-pt/videogoals/blob/master/matches/goals_populator.py#L44) allows for those subtle differences.

#### Potential solutions:
+ Hardcoding regex check for presence of words like U23, U19, W and other indicators we can think of.
+ Does trigram_similarity lookup return elements sorted decreasingly by matching score? If not, it might be better not to take the first result as is done [here](https://github.com/meneses-pt/videogoals/blob/master/matches/goals_populator.py#L48).

Please let me know your thoughts.

**Comment by meneses-pt** [comment]
Yes, this is a bug indeed.
The option for trigram search to fetch teams was intentional, because the names of the teams given by the API and the names of the teams posted on reddit may differ (e.g. Wolverhampton vs Wolves)
Your first potential solution is something I have already thought of, just still didn't have time to implement, but will take a look at it as soon as possible.

**Comment by meneses-pt** [comment]
Solved with commit [https://github.com/meneses-pt/videogoals/commit/50efe9c801ae5666e860e0c982a74e8aace54728]()
